# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052b7e1fab134583a1d9d4193e66a747c237fbb41b4e466d3d362c77c3d03c8ae8837264535a9ae4b9b1aceeb99075ff63f8ce308ba7e8c415a7303db83b0e90

test:
  secret_key_base: 4bb675326a069136a7814d976e5b736e3c0896550d32422fbf1077aedaa6ac51ac88753d20e05f38c1a2caf45a9a1d8752abecdd217dc11bb3e04c7d83c813b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
